---
- name: Delete old users authorized Keys files
  file: path=/home/{{ item }}/.ssh/authorized_keys state=absent
  with_items: users_deleted

- name: Generate sudoers temp file
  command: cp -f /etc/sudoers /etc/sudoers.tmp

- name: Generate sudoers backup file
  command: cp -f /etc/sudoers /etc/sudoers.bak

- name:  Delete old users from sudoers temp file
  lineinfile: dest=/etc/sudoers.tmp state=absent regexp="^{{ item }} ALL\=\(ALL\) NOPASSWD:ALL" line="{{ item }} ALL=(ALL) NOPASSWD:ALL"
  with_items: users_deleted

- name: Replace sudoers by its temp file
  shell: "visudo -q -c -f /etc/sudoers.tmp && cp -f /etc/sudoers.tmp /etc/sudoers"

- name: Delete old users
  user: name={{ item }} shell=/bin/bash state=absent
  with_items: users_deleted
