---

- name: Install Docker Pre Req
  apt:
    update_cache: yes
    name: "{{ item }}"
  loop:
    - "{{ docker_prereq_packages }}"

- name: add GPG key
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

- name: Add Docker Repository
  apt_repository:
    repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu/ bionic stable

- name: Install Docker
  apt:
    name: "{{ item }}"
  loop: "{{ docker_packages }}"
